carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add_cart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.RemoveCartView.as_view(), name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.RemoveCartItemView.as_view(), name='remove_cart_item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

greatkart_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'
urlpatterns = [
    path('place_order/', views.PlaceOrderView.as_view(), name='place_order'),
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('order_complete/', views.OrderCompleteView.as_view(), name='order_complete'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>', views.StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchView.as_view(), name='search')
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='cart_items', null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from store.models import Product
from .models import CartItem, Cart
from django.core.exceptions import ObjectDoesNotExist
from store.models import Variation
from django.contrib.auth.mixins import LoginRequiredMixin
from orders.forms import OrderForm


class CartView(View):
    template_name = 'carts/cart.html'

    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def get(self, request, total=0, quantity=0, cart_items=None, tax=0, grand_total=0):
        try:
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            else:
                cart = Cart.objects.get(cart_id=self._cart_id(request))
                cart_items = CartItem.objects.filter(cart=cart, is_active=True)
            for cart_item in cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = (2 * total)/100
            grand_total = total + tax
        except ObjectDoesNotExist:
            pass
        context = {
            'total':total,
            'quantity':quantity,
            'cart_items':cart_items,
            'tax':tax,
            'grand_total':grand_total
        }
        return render(request, self.template_name, context)


class AddCartView(View):

    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def post(self, request, product_id):
        current_user = request.user
        product = Product.objects.get(id=product_id)
        if current_user.is_authenticated:
            product_variation = []
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_value__iexact=value, variation_category__iexact=key)
                    product_variation.append(variation)
                except Variation.DoesNotExist:
                    pass

            is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
            if is_cart_item_exists:
                cart_item = CartItem.objects.filter(product=product, user=current_user)
                ex_var_list = []
                id = []
                for item in cart_item:
                    existing_variation = item.variations.all()
                    ex_var_list.append(list(existing_variation))
                    id.append(item.id)
                if product_variation in ex_var_list:
                    index = ex_var_list.index(product_variation)
                    item_id = id[index]
                    item = CartItem.objects.get(product=product, id=item_id)
                    item.quantity += 1
                    item.save()
                else:
                    item = CartItem.objects.create(product=product, user=current_user, quantity=1)
                    if len(product_variation) > 0:
                        item.variations.clear()
                        item.variations.add(*product_variation)
                    item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    user=current_user,
                    quantity=1
                )
                if len(product_variation) > 0:
                    cart_item.variations.clear()
                    cart_item.variations.add(*product_variation)
                cart_item.save()
            return redirect('carts:cart')
        else:
            product_variation = []
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_value__iexact=value, variation_category__iexact=key)
                    product_variation.append(variation)
                except Variation.DoesNotExist:
                    pass
            try:
                cart = Cart.objects.get(cart_id=self._cart_id(request))
            except Cart.DoesNotExist:
                cart = Cart.objects.create(
                    cart_id=self._cart_id(request)
                )
            cart.save()
            is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
            if is_cart_item_exists:
                cart_item = CartItem.objects.filter(product=product, cart=cart)
                ex_var_list = []
                id = []
                for item in cart_item:
                    existing_variation = item.variations.all()
                    ex_var_list.append(list(existing_variation))
                    id.append(item.id)
                if product_variation in ex_var_list:
                    index = ex_var_list.index(product_variation)
                    item_id = id[index]
                    item = CartItem.objects.get(product=product, id=item_id)
                    item.quantity += 1
                    item.save()
                else:
                    item = CartItem.objects.create(product=product, cart=cart, quantity=1)
                    if len(product_variation) > 0:
                        item.variations.clear()
                        item.variations.add(*product_variation)
                    item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    cart=cart,
                    quantity=1
                )
                if len(product_variation) > 0:
                    cart_item.variations.clear()
                    cart_item.variations.add(*product_variation)
                cart_item.save()
            return redirect('carts:cart')


class RemoveCartView(View):
    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def get(self, request, product_id, cart_item_id):
        product = get_object_or_404(Product, id=product_id)
        try:
            if request.user.is_authenticated:
                cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)
            else:
                cart = Cart.objects.get(cart_id=self._cart_id(request))
                cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
            else:
                cart_item.delete()
        except:
            pass
        return redirect('carts:cart')


class RemoveCartItemView(View):

    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def get(self, request, product_id, cart_item_id):
        product = get_object_or_404(Product, id=product_id)
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=self._cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        cart_item.delete()
        return redirect('carts:cart')


class CheckoutView(LoginRequiredMixin, View):
    template_name = 'carts/checkout.html'
    login_url = '/accounts/login'
    form_class = OrderForm

    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def get(self, request, total=0, quantity=0, cart_items=None, tax=0, grand_total=0):
        form = self.form_class()
        try:
            if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            else:
                cart = Cart.objects.get(cart_id=self._cart_id(request))
                cart_items = CartItem.objects.filter(cart=cart, is_active=True)
            for cart_item in cart_items:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
            tax = (2 * total)/100
            grand_total = total + tax
        except ObjectDoesNotExist:
            pass
        context = {
            'total':total,
            'quantity':quantity,
            'cart_items':cart_items,
            'tax':tax,
            'grand_total':grand_total,
            'form':form
        }
        return render(request, self.template_name, context)

carts/templates/carts/cart.html
{% extends 'index.html' %}
{% load  static %}
{% load humanize %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            {% if cart_items %}
                <div class="row">
                    <aside class="col-lg-9">
                        <div class="card">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                    <th scope="col" class="text-right" width="200"></th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for i in cart_items %}
                                        <tr>
                                            <td>
                                                <figure class="itemside align-items-center">
                                                    <div class="aside"><img src="{{ i.product.image.url }}" class="img-sm"></div>
                                                    <figcaption class="info">
                                                        <a href="{{ i.product.get_product_detail_url }}" class="title text-dark">{{ i.product.name }}</a>
                                                        {% if i.variations.all %}
                                                            <p class="text-muted small">
                                                                {% for variation in i.variations.all %}
                                                                	{{ variation.variation_category | capfirst }} : {{ variation.variation_value | capfirst }}
                                                                    <br>
                                                                {% endfor %}
                                                            </p>
                                                        {% endif %}
                                                    </figcaption>
                                                </figure>
                                            </td>
                                            <td>
                                                <!-- col.// -->
                                                <div class="col">
                                                    <div class="input-group input-spinner">
                                                        <div class="input-group-prepend">
                                                            <a href="{% url 'carts:remove_cart' i.product.id i.id %}" class="btn btn-light" type="button" id="button-plus"><i
                                                                    class="fa fa-minus"></i></a>
                                                        </div>
                                                        <input type="text" class="form-control" value="{{ i.quantity }}">
                                                        <div class="input-group-append">
                                                            <form action="{% url 'carts:add_cart' i.product.id %}" method="post">
                                                                {% csrf_token %}
                                                                {% for variation in i.variations.all %}
                                                                    <input type="hidden" name="{{ variation.variation_category | lower }}" value="{{ variation.variation_value | capfirst}}">
                                                                {% endfor %}
                                                                <button type="submit" class="btn btn-light" id="button-minus"><i class="fa fa-plus"></i></button>
                                                            </form>
                                                        </div>
                                                    </div> <!-- input-group.// -->
                                                </div> <!-- col.// -->
                                            </td>
                                            <td>
                                                <div class="price-wrap">
                                                    <var class="price">${{ i.sub_total|intcomma }}</var>
                                                    <small class="text-muted"> ${{ i.product.price|intcomma }} each </small>
                                                </div> <!-- price-wrap .// -->
                                            </td>
                                            <td class="text-right">
                                                <a href="{% url 'carts:remove_cart_item' i.product.id i.id %}" onclick="return confirm('Are you sure you want to delete this item?')" class="btn btn-danger"> Remove</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->
                    <aside class="col-lg-3">

                        <div class="card">
                            <div class="card-body">
                                <dl class="dlist-align">
                                    <dt>Total price:</dt>
                                    <dd class="text-right">${{ total|intcomma }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Tax:</dt>
                                    <dd class="text-right"> ${{ tax|intcomma }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>Total:</dt>
                                    <dd class="text-right text-dark b"><strong>${{ grand_total|intcomma }}</strong></dd>
                                </dl>
                                <hr>
                                <p class="text-center mb-3">
                                    <img src="{% static 'img/misc/payments.png' %}" height="26">
                                </p>
                                <a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                            </div> <!-- card-body.// -->
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->


                </div> <!-- row.// -->
            {% else %}
            	<h2 class="text-center">Your Shopping Cart is Empty</h2>
                <br>
                <div class="text-center">
                    <a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
                </div>
            {% endif %} 

            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

carts/templates/carts/checkout.html
{% extends 'index.html' %}
{% load  static %}
{% load humanize %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">
            <div class="row">
                <aside class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title mb-4">Billing Address</h4>
                            {% include 'inc/messages.html' %}
                            <form action="{% url 'orders:place_order' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">First Name</label>
                                        <input type="text" name="first_name" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">Last Name</label>
                                        <input type="text" name="last_name" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">Email</label>
                                        <input type="email" name="email" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">Phone Number</label>
                                        <input type="text" name="phone" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">Address Line 1</label>
                                        <input type="text" name="address_line_1" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">Address Line 2</label>
                                        <input type="text" name="address_line_2" class="form-control">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">City</label>
                                        <input type="text" name="city" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">State</label>
                                        <input type="text" name="state" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">Country</label>
                                        <input type="text" name="country" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <label for="">Order Note</label>
                                    <textarea name="order_note" id="" rows="2" class="form-control"></textarea>
                                </div>

                        </div>
                    </div> <!-- card.// -->
                </aside>
                <aside class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ i.product.image.url }}" class="img-sm">
                                                </div>
                                                <figcaption class="info">
                                                    <a href="{{ i.product.get_product_detail_url }}"
                                                       class="title text-dark">{{ i.product.name }}</a>
                                                    {% if i.variations.all %}
                                                        <p class="text-muted small">
                                                            {% for variation in i.variations.all %}
                                                                {{ variation.variation_category | capfirst }} :
                                                                {{ variation.variation_value | capfirst }}
                                                                <br>
                                                            {% endfor %}
                                                        </p>
                                                    {% endif %}
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <label for="" class="text-center">{{ i.quantity }}</label>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">${{ i.sub_total|intcomma }}</var>
                                                <small class="text-muted"> ${{ i.product.price|intcomma }} each </small>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <button type="submit" name="submit" class="btn btn-primary btn-block">Place Order</button>
                            <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                            </form>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->
                </aside>
            </div> <!-- row.// -->
        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}