carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add_cart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.RemoveCartView.as_view(), name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.RemoveCartItemView.as_view(), name='remove_cart_item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

greatkart_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'
urlpatterns = [
    path('place_order/', views.PlaceOrderView.as_view(), name='place_order'),
    path('payments/', views.PaymentsView.as_view(), name='payments'),
    path('order_complete/', views.OrderCompleteView.as_view(), name='order_complete'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>', views.StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchView.as_view(), name='search')
]

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.first_name


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2',
                  'country', 'state', 'city', 'order_note']

orders/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from carts.models import CartItem
from .forms import OrderForm
from .models import Order, Payment, OrderProduct
from store.models import Product
import datetime
from django.contrib import messages
import json

from orders.utils import order_received_email
from django.http import JsonResponse


class PlaceOrderView(LoginRequiredMixin, View):
    template_name = 'orders/payments.html'
    def post(self, request, total=0, quantity=0):
        # if the user's cart is empty redirect to store page
        user = request.user
        cart_items = CartItem.objects.filter(user=user)
        cart_items_count = cart_items.count()
        if cart_items_count <= 0:
            return redirect('store:store')

        # Calculate the grand total
        tax = 0
        grand_total = 0
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax

        # Save all the billing information inside Order Table if the info is correct
        form = OrderForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            data = Order()
            data.user = user
            data.first_name = cd['first_name']
            data.last_name = cd['last_name']
            data.phone = cd['phone']
            data.email = cd['email']
            data.address_line_1 = cd['address_line_1']
            data.address_line_2 = cd['address_line_2']
            data.country = cd['country']
            data.state = cd['state']
            data.city = cd['city']
            data.order_note = cd['order_note']
            data.order_total = grand_total
            data.tax = tax
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()

            year = int(datetime.date.today().strftime('%Y'))
            month = int(datetime.date.today().strftime('%m'))
            day = int(datetime.date.today().strftime('%d'))
            date = datetime.date(year, month, day)
            current_date = date.strftime('%Y%m%d')
            order_number = current_date + str(data.id)

            data.order_number = order_number
            data.save()

            order = Order.objects.get(user=user, is_ordered=False, order_number=order_number)
            context = {
                'order':order,
                'cart_items':cart_items,
                'total':total,
                'tax':tax,
                'grand_total':grand_total
            }
            return render(request, self.template_name, context)
        else:
            messages.error(request, 'I do not know but something is wrong!')
            return render(request, 'carts/checkout.html')


class PaymentsView(LoginRequiredMixin, View):
    template_name = 'orders/payments.html'

    def get(self, request):
        body = json.loads(request.body)
        order = Order.objects.get(user=request.user, is_ordered=False, order_number=body['order_id'])

        # save transaction details inside Payment table
        payment = Payment(
            user = request.user,
            payment_id=body['transID'],
            payment_method=body['payment_method'],
            amount_paid=order.order_total,
            status=body['status'],
        )
        payment.save()

        # update some field of Order table
        order.payment = payment
        order.is_ordered = True
        order.save()

        # Move the cart items to Order Product table
        cart_items = CartItem.objects.filter(user=request.user)
        for item in cart_items:
            order_product = OrderProduct()
            order_product.order_id = order.id
            order_product.payment = payment
            order_product.user_id = request.user.id
            order_product.product_id = item.product_id
            order_product.quantity = item.quantity
            order_product.product_price = item.product_price
            order_product.ordered = True
            order_product.save()

            cart_item = CartItem.objects.get(id=item.id)
            product_variation = cart_item.variations.all()
            order_product = OrderProduct.objects.get(id=order_product.id)
            order_product.variations.set(product_variation)
            order_product.save()

            # Reduce the quantity of the sold products
            product = Product.objects.get(id=item.product_id)
            product.stock -= item.quantity
            product.save()

        # Clear cart
        CartItem.objects.filter(user=request.user).delete()

        # Send order received email to customer
        order_received_email(request, order)

        # Send order number and transaction id back to sendData method via JsonRequest
        data = {
            'order_number':order.order_number,
            'transID':payment.payment_id,
        }
        return JsonResponse(data)


class OrderCompleteView(LoginRequiredMixin, View):
    template_name = 'orders/order_complete.html'

    def get(self, reqeust):
        order_number = reqeust.GET.get('order_number')
        transID = reqeust.GET.get('payment_id')

        try:
            order = Order.objects.get(order_number=order_number, is_ordered=True)
            ordered_products = OrderProduct.objects.filter(order_id=order.id)
            sub_total = 0
            for item in ordered_products:
                sub_total += item.product_price * item.quantity
            payment = Payment.objects.get(payment_id=transID)
            context = {
                'order':order,
                'ordered_products':ordered_products,
                'order_number':order.order_number,
                'transID':payment.payment_id,
                'payment':payment,
                'sub_total':sub_total
            }
            return render(reqeust, self.template_name, context)
        except (Payment.DoesNotExist, Order.DoesNotExist):
            return redirect('home')

    def post(self, request):
        pass

orders/templates/orders/order_complete.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 50px;">
        <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
        <h2 class="text-center">Payment Successful</h2>
        <br>
        <div class="text-center">
            <a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
        </div>
    </div>

    <div class="container"
         style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
        <div class="row invoice row-printable">
            <div class="col-md-12">
                <!-- col-lg-12 start here -->
                <div class="panel panel-default plain" id="dash_0">
                    <!-- Start .panel -->
                    <div class="panel-body p30">
                        <div class="row">
                            <!-- Start .row -->
                            <div class="col-lg-6">
                                <!-- col-lg-6 start here -->
                                <div class="invoice-logo"><img src="{% static 'img/logo.png' %}" alt="Invoice logo"
                                                               style="max-height: 40px;"></div>
                            </div>
                            <!-- col-lg-6 end here -->
                            <div class="col-lg-6">
                                <!-- col-lg-6 start here -->
                                <div class="invoice-from">
                                    <ul class="list-unstyled text-right">
                                        <li><strong>Invoiced To</strong></li>
                                        <li>{{ order.full_name }}</li>
                                        <li>{{ order.full_address }}</li>
                                        <li>{{ order.city }}</li>
                                        <li>{{ order.state }}</li>
                                        <li>{{ order.country }}</li>
                                    </ul>
                                </div>
                            </div>
                            <!-- col-lg-6 end here -->
                            <div class="col-lg-12">
                                <!-- col-lg-12 start here -->
                                <div class="invoice-details mt25">
                                    <div class="well">
                                        <ul class="list-unstyled mb0">
                                            <li><strong>Order</strong> #{{ order_number }}</li>
                                            <li><strong>Transaction ID</strong> #{{ transID }}</li>
                                            <li><strong>Order Date:</strong> {{ order.created_at }}</li>
                                            <li><strong>Status:</strong> {{ payment.status }}</li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="invoice-items">
                                    <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                        <table class="table table-bordered">
                                            <thead>
                                            <tr>
                                                <th class="per70 text-center">Products</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in order_products %}
                                                <tr>
                                                    <td>{{ item.product.product_name }}
                                                        <p class="text-muted small">
                                                            {% if item.variations.all %}
                                                                {% for i in item.variations.all %}
                                                                    {{ i.variation_category | capfirst }} :
                                                                    {{ i.variation_value | capfirst }}
                                                                    <br>
                                                                {% endfor %}
                                                            {% endif %}
                                                        </p>
                                                    </td>
                                                    <td class="text-center">{{ item.quantity }}</td>
                                                    <td class="text-center">${{ item.product_price }} USD</td>
                                                </tr>
                                            {% endfor %}

                                            </tbody>
                                            <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">${{ sub_total }} USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">${{ order.tax }} USD</th>
                                            </tr>

                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">${{ order.order_total }} USD</th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                                <div class="invoice-footer mt25">
                                    <p class="text-center">Thank you for shopping with us!</p>
                                </div>
                            </div>
                            <!-- col-lg-12 end here -->
                        </div>
                        <!-- End .row -->
                    </div>
                </div>
                <!-- End .panel -->
            </div>
            <!-- col-lg-12 end here -->
        </div>
    </div>
{% endblock %}

orders/templates/orders/order_received_email.html
{% autoescape off %}
    Hi {{ user.first_name }},

    YOUR ORDER HAS BEEN RECEIVED

    Order Number: {{ order.order_number }}

{% endautoescape %}

orders/templates/orders/payments.html
{% extends 'index.html' %}
{% load  static %}
{% load humanize %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            <h4 class="text-center mb-10">Review Your Order And Make Payment</h4>
            <div class="row">
                <aside class="col-lg-8">
                    <div class="card">
                        <h5 class="card-header">Billing Address</h5>
                        <div class="card-body">
                            <p class="card-text mb-0">{{ order.full_name }}</p>
                            <p class="card-text mb-0">{{ order.full_address }}</p>
                            <p class="card-text mb-0">{{ order.city }}, {{ order.state }}</p>
                            <p class="card-text mb-0">{{ order.country }}</p>
                            <p class="card-text mb-0">{{ order.email }}</p>
                            <p class="card-text mb-0">{{ order.phone }}</p>
                            {% if order.order_note %}
                                <p class="card-text mb-0"><b>Order Note: </b> {{ order.order_note }}</p>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card">
                        <h5 class="card-header">Payment Methods</h5>
                        <div class="card-body">
                            <p class="card-text">PayPal</p>
                        </div>
                    </div>
                    <div class="card">
                        <h5 class="card-header">Review Products</h5>
                        <div class="card-body">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ i.product.image.url }}" class="img-sm">
                                                </div>
                                                <figcaption class="info">
                                                    <a href="{{ i.product.get_product_detail_url }}"
                                                       class="title text-dark">{{ i.product.name }}</a>
                                                    {% if i.variations.all %}
                                                        <p class="text-muted small">
                                                            {% for variation in i.variations.all %}
                                                                {{ variation.variation_category | capfirst }} :
                                                                {{ variation.variation_value | capfirst }}
                                                                <br>
                                                            {% endfor %}
                                                        </p>
                                                    {% endif %}
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <label for="" class="text-center">{{ i.quantity }}</label>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">${{ i.sub_total|intcomma }}</var>
                                                <small class="text-muted"> ${{ i.product.price|intcomma }} each </small>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </aside> <!-- col.// -->
                <aside class="col-lg-4">

                    <div class="card">
                        <div class="card-body">
                            <dl class="dlist-align">
                                <dt>Total price:</dt>
                                <dd class="text-right">${{ total|intcomma }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Tax:</dt>
                                <dd class="text-right"> ${{ tax|intcomma }}</dd>
                            </dl>
                            <dl class="dlist-align">
                                <dt>Total:</dt>
                                <dd class="text-right text-dark b"><strong>${{ grand_total|intcomma }}</strong></dd>
                            </dl>
                            <hr>
                            <p class="text-center mb-3">
                                <img src="{% static 'img/misc/payments.png' %}" height="26">
                            </p>
                            <div id="paypal-button-container">


                            </div>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
            </div> <!-- row.// -->

            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        // Render the PayPal button into #paypal-button-container
        var amount = "{{ grand_total }}"
        var url = "{% url 'orders:payments' %}"
        var csrftoken = getCookie('csrftoken');
        var orderID = "{{ order.order_number }}"
        var payment_method = 'PayPal'
        var redirect_url = '{% url 'orders:order_complete' %}'


        paypal.Buttons({
            style: {
                color: 'blue',
                shape: 'pill',
                label: 'pay',
                height: 40
            },
            // Call your server to set up the transaction
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase: [{
                        amount: {
                            value: amount,
                        }
                    }]
                });
            },

            // Call your server to finalize the transaction
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (details) {
                    console.log(details);
                    sendData();

                    function sendData() {
                        fetch(url, {
                            method: 'POST',
                            headers: {
                                "Content-type": "application/json",
                                "X-CSRFToken": csrftoken,
                            },
                            body: JSON.stringify({
                                orderID: orderID,
                                transID: details.id,
                                payment_method: payment_method,
                                status: details.status,
                            }),
                        })
                            .then((response) => response.json())
                            .then((data) => {
                                window.location.href = redirect_url + '?order_number='+data.order_number+'&payment_id='+data.transID;
                            });
                    }
                });
            }

        }).render('#paypal-button-container');
    </script>
{% endblock %}