accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('confirm/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    path('', views.DashboardView.as_view(), name='dashboard'),

    # Password reset
    path('pass_reset/', views.PassResetView.as_view(), name='pass_reset'),
    path('pass_reset_done/', views.PassResetDoneView.as_view(), name='pass_reset_done'),
    path('pass_reset_confirm/<uidb64>/<token>/', views.PassResetConfirmView.as_view(), name='pass_reset_confirm'),
    path('pass_reset_complete/', views.PassResetCompleteView.as_view(), name='pass_reset_complete'),

    # Dashboard
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('my_orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('order_detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),

]

carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add_cart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.RemoveCartView.as_view(), name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.RemoveCartItemView.as_view(), name='remove_cart_item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

greatkart_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class AccountManger(BaseUserManager):
    def create_user(self, first_name, last_name, email, username, password):
        if not email:
            raise ValueError('User must have an email address')
        if not username:
            raise ValueError('User must have an username')
        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
            username=username,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = AccountManger()

    def __str__(self):
        return self.email

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100, blank=True)
    address_line_2 = models.CharField(max_length=100, blank=True)
    profile_picture = models.ImageField(blank=True, upload_to='profile_picture')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

accounts/forms.py
from django import forms
from .models import Account, UserProfile
from django.core.exceptions import ValidationError


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

            # Placeholder
            alist = field.split('_')
            s = ' '.join(i.capitalize() for i in alist)
            self.fields[field].widget.attrs['placeholder'] = f'Enter {s}'

    def clean(self):
        cd = super().clean()
        ps1 = cd.get('password')
        ps2 = cd.get('confirm_password')
        if ps2 != ps1:
            raise forms.ValidationError(
                "Password does not match"
            )

    def clean_email(self):
        new_email = self.cleaned_data['email']
        user = Account.objects.filter(email__exact=new_email).exists()
        if user:
            raise forms.ValidationError(
                "Email has already exists"
            )
        return new_email


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class':'form-control',
        'placeholder':'Email'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class':'form-control',
        'placeholder':'Password'
    }))


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'Invalid':('Image files only')}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ['address_line_1', 'address_line_2', 'city', 'state', 'country', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import RegistrationForm, LoginForm, UserProfileForm, UserForm
from .models import Account, UserProfile
from orders.models import OrderProduct, Order
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.utils import user_activation, user_pass_reset
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from carts.models import Cart, CartItem
from orders.models import Order



class RegisterView(View):
    template_name = 'accounts/register.html'
    form_class = RegistrationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        context = {
            'form':form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            user = Account.objects.create_user(
                first_name=cd['first_name'],
                last_name=cd['last_name'],
                email=cd['email'],
                username=cd['email'].split('@')[0],
                password=cd['password']
            )
            user.phone_number = cd['phone_number']
            user.save()
            # messages.success(request, 'Email was sent.')
            # User activation
            user_activation(request, cd['email'], user)

            # messages.success(request, 'THank you for registering with us. We have sent you a verification email to your email address. Please verify it.')
            return redirect(f'/accounts/login/?command=verification&email={cd["email"]}')

        context = {
            'form':form
        }
        return render(request, self.template_name, context)


class LoginView(View):
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def _cart_id(self, request):
        cart = request.session.session_key
        if not cart:
            cart = request.session.create()
        return cart

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        try:
            next_url = request.GET.get('next')
            request.session['next_url'] = next_url
        except:
            pass

        form = self.form_class()
        context = {
            'form':form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd['email']
            password = cd['password']

            user = authenticate(email=email, password=password)
            if user is not None:
                try:
                    cart = Cart.objects.get(cart_id=self._cart_id(request))
                    is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                    if is_cart_item_exists:
                        cart_items = CartItem.objects.filter(cart=cart)
                        product_variation = []
                        for item in cart_items:
                            variation = item.variations.all()
                            product_variation.append(list(variation))
                        cart_items = CartItem.objects.filter(user=user)
                        ex_var_list = []
                        id = []
                        for item in cart_items:
                            variation = item.variations.all()
                            ex_var_list.append(list(variation))
                            id.append(item.id)

                        for pr in product_variation:
                            if pr in ex_var_list:
                                index = ex_var_list.index(pr)
                                item_id = id[index]
                                item = CartItem.objects.get(id=item_id)
                                item.quantity += 1
                                item.user = user
                                item.save()
                            else:
                                cart_items = CartItem.objects.filter(cart=cart)
                                for item in cart_items:
                                    item.user = user
                                    item.save()
                except:
                    pass
                login(request, user)
                try:
                    next_url = request.session.get('next_url')
                    messages.success(request, 'You are now logged in.')
                    return redirect(next_url)
                except:
                    messages.success(request, 'You are now logged in.')
                    return redirect('accounts:dashboard')
            else:
                messages.error(request, 'Invalid login credentials')
                return redirect('accounts:login')
        context = {
            'form':form
        }
        return render(request, self.template_name, context)


class LogoutView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    def get(self, request):
        logout(request)
        messages.success(request, 'You are logged out.')
        return redirect('home')


class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = Account.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
            user = None
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Congratulations! Your account is activated')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Invalid activation link')
            return redirect('accounts:register')


class DashboardView(LoginRequiredMixin, View):
    template_name = 'accounts/dashboard.html'

    def get(self, request):
        orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
        orders_count = orders.count()
        try:
            user_profile = UserProfile.objects.get(user_id=request.user.id)
        except:
            user_profile = None
        context = {
            'orders':orders,
            'orders_count':orders_count,
            'user_profile':user_profile
        }
        return render(request, self.template_name, context)

class MyOrdersView(LoginRequiredMixin, View):
    template_name = 'accounts/my_orders.html'
    def get(self, request):
        orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
        context = {
            'orders':orders
        }
        return render(request, self.template_name, context)


class EditProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/edit_profile.html'
    form_class1 = UserForm
    form_class2 = UserProfileForm

    def setup(self, request, *args, **kwargs):
        self.user_profile = get_object_or_404(UserProfile, user=request.user)
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        user_form = self.form_class1(instance=request.user)
        profile_form = self.form_class2(instance=self.user_profile)
        context = {
            'user_form':user_form,
            'profile_form':profile_form,
            'user_profile':self.user_profile
        }
        return render(request, self.template_name, context)

    def post(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)

        user_form = self.form_class1(request.POST, instance=request.user)
        profile_form = self.form_class2(request.POST, request.FILES, instance=user_profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit_profile')
        context = {
            'user_form':user_form,
            'profile_form':profile_form
        }
        return render(request, self.template_name, context)


class PassResetView(View):
    template_name = 'accounts/pass_reset.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You do not have access to this page')
            return redirect('accounts:dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST['email']
        user = Account.objects.filter(email=email).exists()
        if user:
            user = Account.objects.get(email__iexact=email)
            user_pass_reset(request, email, user)
            return redirect('accounts:pass_reset_done')

        else:
            messages.error(request, 'Account does not exist.')
            return redirect('accounts:pass_reset')


class PassResetDoneView(View):
    template_name = 'accounts/pass_reset_done.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You do not have access to this page')
            return redirect('accounts:dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}
 Hi {{ user.first_name }},

 Please click on below link to confirm your registration
 http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

if you think it's not you, please ignore this email.
{% endautoescape %}

accounts/templates/accounts/change_password.html
{% extends 'index.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-conten padding-y bg">
        {% include 'inc/messages.html' %}
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <!--   SIDEBAR   -->
                    {% include 'accounts/inc/dashboard_sidebar.html' %}
                    <br>
                    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i
                            class="fa fa-power-off"></i> <span class="text">Log out</span>
                    </a>
                    <!--   SIDEBAR .//END   -->
                </aside>
                <main class="col-md-9">
                    <article class="card">
                        <header class="card-header">
                            <strong class="d-inline-block mr-3">Change Your Password</strong>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form action="{% url 'accounts:change_password' %}" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label>Current Password</label>
                                            <input type="password" name="current_password"
                                                   placeholder="current Password" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Create New Password</label>
                                            <input type="password" name="new_password"
                                                   placeholder="Create New Password" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Confirm New Password</label>
                                            <input type="password" name="confirm_password"
                                                   placeholder="Confirm New Password" class="form-control" required>
                                        </div>
                                        <input type="submit" VALUE="Save" class="btn btn-primary">
                                    </form>
                                </div>
                            </div> <!-- row.// -->
                        </div> <!-- card-body .// -->
                    </article> <!-- order-group.// -->
                </main>
            </div> <!-- row.// -->
        </div>


    </section>
{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'index.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-conten padding-y bg">
        {% include 'inc/messages.html' %}
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <!--   SIDEBAR   -->
                    {% include 'accounts/inc/dashboard_sidebar.html' %}
                    <br>
                    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i
                            class="fa fa-power-off"></i> <span class="text">Log out</span>
                    </a>
                    <!--   SIDEBAR .//END   -->
                </aside>
                <main class="col-md-9">
                    <article class="card">
                        <header class="card-header">
                            <strong class="d-inline-block mr-3">Logged in as: </strong>
                            <span>{{ request.user.full_name }}</span>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="card" style="text-align: center">
                                        <div class="card-body">
                                            <h5 class="card-title">Total Orders</h5>
                                            {% if orders_count > 0 %}
                                                <h4>{{ orders_count }}</h4>
                                                <a href="{% url 'accounts:my_orders' %}">View Orders</a>
                                            {% else %}
                                                <h4>0</h4>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="card" style="text-align: center">
                                        <div class="card-body">
                                            <img src="{{ user_profile.profile_picture.url }}"
                                                 alt="User Profile Picture" width="50" height="50"
                                                 style="border-radius: 50%">
                                            <p class="mb-0">{{ request.user.email }}</p>
                                            <p>{{ request.user.phone_number }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div> <!-- row.// -->
                        </div> <!-- card-body .// -->

                    </article> <!-- order-group.// -->
                </main>
            </div> <!-- row.// -->
        </div>


    </section>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'index.html' %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-conten padding-y" style="min-height:84vh">
        {% if request.GET.command == 'verification' %}
            <div class="container mx-auto alert alert-info text-center" role='alert' style="max-width: 1024px; margin-top:100px;">
                Thank you for registering with us. We have sent you a verification email to your email address
                [{{ request.GET.email }}].
                <br><br>
                Already verified? <a href="{% url 'accounts:login' %}">Login</a>
            </div>
        {% else %}
            <!-- ============================ COMPONENT LOGIN   ================================= -->
            <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
                <div class="card-body">
                    <h4 class="card-title mb-4">Sign in</h4>
                    {% include 'inc/messages.html' %}
                    <form action="{% url 'accounts:login' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.email }}
                        </div> <!-- form-group// -->
                        <div class="form-group">
                            {{ form.password }}
                        </div> <!-- form-group// -->

                        <div class="form-group">
                            <a href="{% url 'accounts:pass_reset' %}" class="float-right">Forgot password?</a>

                        </div> <!-- form-group form-check .// -->
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Login</button>
                        </div> <!-- form-group// -->
                    </form>
                </div> <!-- card-body.// -->
            </div> <!-- card .// -->

            <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
            <br><br>
            <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
        {% endif %}

    </section>
{% endblock %}

accounts/templates/accounts/my_orders.html
{% extends 'index.html' %}
{% load static %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-conten padding-y bg">
        {% include 'inc/messages.html' %}
        <div class="container">
            <div class="row">
                <aside class="col-md-3">
                    <!--   SIDEBAR   -->
                    {% include 'accounts/inc/dashboard_sidebar.html' %}
                    <br>
                    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i
                            class="fa fa-power-off"></i> <span class="text">Log out</span>
                    </a>
                    <!--   SIDEBAR .//END   -->
                </aside>
                <main class="col-md-9">
                    <article class="card">
                        <header class="card-header">
                            <strong class="d-inline-block mr-3">Your order history</strong>
                        </header>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th scope="col">Order #</th>
                                            <th scope="col">Billing Name</th>
                                            <th scope="col">Phone</th>
                                            <th scope="col">Order Total</th>
                                            <th scope="col">Date</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for order in orders %}
                                            <tr>

                                                <th scope="row"><a href="{% url 'accounts:order_detail' order.order_number %}">{{ order.order_number }}</a></th>
                                                <th>{{ order.full_name }}</th>
                                                <th>{{ order.phone }}</th>
                                                <th>{{ order.order_total }}</th>
                                                <th>{{ order.created_at }}</th>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div> <!-- row.// -->
                        </div> <!-- card-body .// -->
                    </article> <!-- order-group.// -->
                </main>
            </div> <!-- row.// -->
        </div>


    </section>
{% endblock %}

accounts/templates/accounts/pass_reset_complete.html
{% extends 'index.html' %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="container mx-auto alert alert-info text-center" role='alert' style="max-width: 80%; margin-top:50px; margin-bottom: 35%">
        Your password has been changed successfully. Please <a href="{% url 'accounts:login' %}" class="alert-link">Login</a>
    </div>
{% endblock %}

accounts/templates/accounts/pass_reset_confirm.html
{% extends 'index.html' %}
{% block title %}

{% endblock %}
{% block content %}
    <section class="section-conten padding-y" style="min-height:84vh">
        <!-- ============================ COMPONENT Forgot password   ================================= -->
        <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
            <div class="card-body">
                <h4 class="card-title mb-4">Password Reset Confirm</h4>
                {% include 'inc/messages.html' %}
                <form action="{% url 'accounts:pass_reset_confirm' uidb64 token%}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="password" placeholder="New password" class="form-control" name="password">
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        <input type="password" placeholder="Confirm new password" class="form-control" name="confirm_password">
                    </div> <!-- form-group// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Reset Password</button>
                    </div> <!-- form-group// -->
                </form>
            </div> <!-- card-body.// -->
        </div> <!-- card .// -->

        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    </section>
{% endblock %}

accounts/templates/accounts/pass_reset_email.html
{% autoescape off %}
    You're receiving this email because you requested a password reset for your user account at 127.0.0.1:8000.
    Please go to the following page and choose a new password:
    http://{{ domain }}{% url 'accounts:pass_reset_confirm' uidb64=uid token=token %}
    if you think it's not you, please ignore this email!!!
    Thanks for using our site!
{% endautoescape %}