accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('confirm/<uidb64>/<token>/', views.ActivateView.as_view(), name='activate'),
    path('', views.DashboardView.as_view(), name='dashboard'),

    # Password reset
    path('pass_reset/', views.PassResetView.as_view(), name='pass_reset'),
    path('pass_reset_done/', views.PassResetDoneView.as_view(), name='pass_reset_done'),
    path('pass_reset_confirm/<uidb64>/<token>/', views.PassResetConfirmView.as_view(), name='pass_reset_confirm'),
    path('pass_reset_complete/', views.PassResetCompleteView.as_view(), name='pass_reset_complete'),

    # Dashboard
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('my_orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('order_detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),

]

carts/urls.py
from django.urls import path
from . import views
app_name = 'carts'
urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add_cart/<int:product_id>/', views.AddCartView.as_view(), name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.RemoveCartView.as_view(), name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.RemoveCartItemView.as_view(), name='remove_cart_item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

greatkart_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('store/', include('store.urls', namespace='store')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.StoreView.as_view(), name='store'),
    path('category/<slug:category_slug>', views.StoreView.as_view(), name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.ProductDetailView.as_view(), name='product_detail'),
    path('search/', views.SearchView.as_view(), name='search')
]

templates/inc/footer.html
<footer class="section-footer border-top">
    <div class="container">
        <section class="footer-bottom border-top row">
            <div class="col-md-2">
                <p class="text-muted"> &copy 2019 Company name </p>
            </div>
            <div class="col-md-8 text-md-center">
                <span class="px-2">info@pixsellz.io</span>
                <span class="px-2">+879-332-9375</span>
                <span class="px-2">Street name 123, Avanue abc</span>
            </div>
            <div class="col-md-2 text-md-right text-muted">
                <i class="fab fa-lg fa-cc-visa"></i>
                <i class="fab fa-lg fa-cc-paypal"></i>
                <i class="fab fa-lg fa-cc-mastercard"></i>
            </div>
        </section>
    </div><!-- //container -->
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('.thumb a').click(function (e){
            e.preventDefault();
            $('.mainImage img').attr('src', $(this).attr("href"));
        })
    })
</script>

templates/inc/head_tag.html
{% load static %}
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache"/>
<meta http-equiv="cache-control" content="max-age=604800"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)"/>
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>


<script type="text/javascript">
    /// some script

    // jquery ready start
    $(document).ready(function () {
        // jQuery code

    });
    // jquery end
</script>

templates/inc/header.html
{% load static %}
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> English </a>

                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> USD </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'img/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'store:store' %}">All Products </a>
                            {% for category in categories %}
                                <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{category.category_name}} </a>
                            {% endfor %}


                        </div>
                    </div>  <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'store:search' %}" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if request.user.is_authenticated %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome <strong>{{ request.user.first_name }}</strong></small>
                                <div>
                                    <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:logout' %}"> Logout</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome guest!</small>
                                <div>
                                    <a href="{% url 'accounts:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:register' %}"> Register</a>
                                </div>
                            </div>
                        {% endif %}

                        <a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->


</header> <!-- section-header.// -->

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
                </button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}
{#{% if messages %}#}
{#    {% for message in messages %}#}
{#        <p class="alert alert-success">{{ message }}</p>#}
{#    {% endfor %}#}
{#{% endif %}#}
{#{% if messages %}#}
{#    <div class="messages">#}
{#        {% for message in messages %}#}
{#            <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
{#                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}#}
{#                {{ message }}#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#{% endif %}#}